Design: uStreamer Debian package.
tiny-pilot/ustreamer-debian pull request #2
Opened 2023-03-29 16:04 UTC by jdeanwallace

Resolves https://github.com/tiny-pilot/ustreamer-debian/issues/1

2023-04-04 20:49 UTC, mtlynch requested changes
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/ustreamer-debian/2)



<hr />

In: **DEBIAN-PKG.md**:
Can we add a `Background` section that explains why we're doing this?

<hr />

In: **DEBIAN-PKG.md**:

```
> Line 12
4. Consolidate `ansible-role-ustreamer` repo with TinyPilot repo
```
Can we move these steps into the headings below like:

```markdown
## Milestone 1: Install uStreamer via a Debian package instead of compiling from source
```

<hr />

In: **DEBIAN-PKG.md**:
It's a little unclear what happens at the end of each milestone. Can we break it up like:

```markdown
## Milestone 1: Blah blah

### Goal

...

### Steps

...
```

I think that would make the phases feel more clear to me in terms of what benefit we gain in each milestone.

<hr />

In: **DEBIAN-PKG.md**:

```
> Line 53
  - uStreamer can now load a custom EDID before it starts, so it might make sense to keep the EDID in the uStreamer Debian package. See https://github.com/pikvm/ustreamer#edid
```
It looks like this only works when running uStreamer under Docker: https://github.com/pikvm/ustreamer/pull/179/files

<hr />

In: **DEBIAN-PKG.md**:

```
> Line 78
- Consolidate `ansible-role-ustreamer` repo with TinyPilot repo
```
Can we get rid of the ansible role entirely? What would remain of the role at this point?


<hr />

👀 @jdeanwallace it's your turn please take a look

2023-04-06 16:52 UTC, jdeanwallace reviewed
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/ustreamer-debian/2)



<hr />

In: **DEBIAN-PKG.md**:
Done.

<hr />

In: **DEBIAN-PKG.md**:
Ah right, thanks. Removed.

<hr />

In: **DEBIAN-PKG.md**:
Good point. Not sure what I was thinking. Removed.

<hr />

In: **DEBIAN-PKG.md**:
Done.

<hr />

In: **DEBIAN-PKG.md**:
Done. Thanks, defining the goals helped me better structure the milestones and steps. I've made some substantial changes.


<hr />

👀 @mtlynch it's your turn please take a look

2023-04-06 22:36 UTC, mtlynch requested changes
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/ustreamer-debian/2)



Cool, nice updates!

<hr />

In: **DEBIAN-PKG.md**:

```
> Line 31
    - Save the package file as an CI artifact which we can later manually attach to as GitHub release asset
```
I can't tell if we're planning to automate this at some point. Are we?

Manually adding release files for a single release is fine, but I want to avoid adding a manual task like that to our regular release process.

<hr />

In: **DEBIAN-PKG.md**:

```
> Line 75
## Milestone 3: Migrate all uStreamer Ansible role functionality to Debian package
```
With this fleshed out a little more, it sounds like it's going to be harder than I thought to drop the Ansible role entirely.

I think we'll likely get it to a point similar to where we are with ansible-role-tinypilot in that we have both the Ansible role and the Debian package, and it would be *nice* to get rid of the Ansible role, but there are other tasks that are higher in priority.

So maybe we break milestone 3 into two milestones where the first is limited to things that have a good ROI . By that I mean things that are annoying enough to keep in Ansible that we'll prioritize Debianizing them or they're easy enough to Debianize that we might as well (e.g. managing `ustreamer` user+group in Debian package instead of Ansible). And then milestone 4 can be like a "clean up when we have time" of getting rid of all the remaining stuff that isn't too annoying to keep as Ansible.


<hr />

👀 @jdeanwallace it's your turn please take a look

2023-04-07 15:00 UTC, jdeanwallace reviewed
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/ustreamer-debian/2)



<hr />

In: **DEBIAN-PKG.md**:
Yes, we'll only be adding a release file manually for a single release. Once we've consolidated `ansible-role-ustreamer` with the TinyPilot repo, in milestone 2, the manual process will no longer be needed.

I've added a bullet point to make that clear.

<hr />

In: **DEBIAN-PKG.md**:
Done. Besides building uStreamer on the device, uStreamer's Ansible tasks don't seem that annoying.

I've tried my best to move low-effort/modular Ansible tasks into milestone 3, but I could only find 2 independent tasks. The rest of the tasks are tightly coupled to dynamically determined Ansible variables (like `ustreamer_capture_device`) which makes the migration task "tricky" and probably not a good ROI. So I kept the remaining "tricky" tasks in milestone 4 😬.


<hr />

👀 @mtlynch it's your turn please take a look

2023-04-07 16:13 UTC, mtlynch approved these changes
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/ustreamer-debian/2)


<a href="https://codeapprove.com/pr/tiny-pilot/ustreamer-debian/2"><img src="https://codeapprove.com/external/github-stamp-allbg.png" width="159" alt="Approved on CodeApprove" /></a>
✔️ Approved

LGTM, thanks!

<hr />

👀 @jdeanwallace it's your turn please take a look

2023-04-07 16:13 UTC, mtlynch commented
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/ustreamer-debian/2)

⏳ @jotaen4tinypilot please review this Pull Request

2023-04-07 16:14 UTC, mtlynch commented
@jotaen4tinypilot - Can you take a pass on this? For design reviews, I think it's worth having a second review.

2023-04-10 13:17 UTC, jdeanwallace reviewed
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/ustreamer-debian/2)



<hr />

In: **Discussion**
That's correct. Updating video settings is now taken care of by the uStreamer launcher script, which dynamically determines the video settings when the script starts up (https://github.com/tiny-pilot/tinypilot/pull/1252).

And the uStreamer launcher script will be migrated to the uStreamer Debian package in Milestone 4.

<hr />

In: **DEBIAN-PKG.md**:
Sorry, I'm not sure I follow when you say "suggests that this aspect would be relevant in Milestone 1 already".

What I mean by "parallel changes" is that if we migrate a feature to `ustreamer-debian` we then need to bump its version number and update `ansible-role-ustreamer` to point to the new version of the uStreamer Debian package. In Milestone 1, we do this once by creating a manual `ustreamer-debian` release and then updating `ansible-role-ustreamer` to install the appropriate uStreamer Debian package.

So If we merge the two repos, we can avoid making these changes in both repos for each migrated feature.

I've slightly updated Milestone 2's goal to help clarify (https://github.com/tiny-pilot/ustreamer-debian/pull/2/commits/870607c67d766ae7867d22f4e0725a9ceeb252ba).

<hr />

In: **DEBIAN-PKG.md**:

```
> Line 72
- Archive `ustreamer-debian` repo
```
Yeah that should also work fine, essentially doing milestone 2 first then milestone 1. However, I've scheduled milestone 1 first because it delivers the most value (i.e., reduce install time) in, what I think might be, the shortest dev time. 

This decision is based one of the original [task considerations](https://github.com/tiny-pilot/ustreamer-debian/issues/1#issue-1584916275):
> The highest priority item is compiling the uStreamer binary ahead of time rather than on the user's device


I've added an extra sentence to milestone 1's goal to make the above clear (https://github.com/tiny-pilot/ustreamer-debian/pull/2/commits/11e544587f41f1d39b273febe91648dc8f9a3602).


<hr />

👀 @jotaen4tinypilot it's your turn please take a look

2023-04-11 11:56 UTC, jdeanwallace reviewed
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/ustreamer-debian/2)



<hr />

In: **DEBIAN-PKG.md**:
Oh yes, thanks for clarifying. I've updated milestone 1 to mention that we still want to maintain building from source.

2023-04-11 12:30 UTC, jdeanwallace commented
Thanks for the reviews!

I've created the [uStreamer Debian package: MEGA-TICKET](https://github.com/tiny-pilot/tinypilot/issues/1353) and the individual tickets for each step of Milestone 1.

2023-04-11 12:30 UTC, closed without merging