Document testing process for candidate releases
tiny-pilot/ustreamer-debian pull request #20
Opened 2024-04-19 14:32 UTC by db39

2024-04-24 03:09 UTC, cghague requested changes
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/ustreamer-debian/20)



<hr />

In: **README.md**:

```
> Line 20
Open a GitHub comparison showing the commits since the last version of uStreamer TinyPilot uses to the latest tagged version e.g., [v5.43 to v6.11](https://github.com/pikvm/ustreamer/compare/v5.43...v6.11). Review the commit messages for any breaking changes or feature improvements.
```
I found the first sentence awkward to parse. Suggest `Review all commits made to uStreamer since we last cut a release. You can do this using a GitHub comparison, e.g., [v5.43 to v6.11](https://github.com/pikvm/ustreamer/compare/v5.43...v6.11).`

<hr />

In: **README.md**:

```
> Line 26
If the new version of uStreamer doesn't have any obvious breaking changes, create a new uStreamer debian package in a development branch.
```
Nit: Suggest adding `as follows` to the end of this line for clarity.

<hr />

In: **README.md**:

```
> Line 38
Create a new branch in this repository and update the `ARG PKG_VERSION=` line in `Dockerfile` to the desired [uStreamer release tag](https://github.com/pikvm/ustreamer/tags).
```
Nit: Suggest adding `Then, ` to the start of this line for clarity.

<hr />

In: **README.md**:

```
> Line 42
When you have a branch for the new TinyPilot uStreamer Debian package, install the test package on a live device and test it.
```
This line feels redundant and mildly confusing. Suggest dropping it and updating the section header to `Testing on device`.

<hr />

In: **README.md**:

```
> Line 46
Download the TinyPilot uStreamer debian package.
```
Suggest `Get the URL of the new debian package.`.

<hr />

In: **README.md**:

```
> Line 53
Run:
```
Suggest `Download the new debian package on the test device`.

<hr />

In: **README.md**:

```
> Line 68
Now perform a manual test of TinyPilot's video features (a subset of our manual release testing process) to make sure they still work as expected.
```
Some testing steps assume the reader uses Ubuntu 22.04 as the target operating system. I suspect this is because they're the same as the customer support team's instructions. It's not worth updating them to be more generic, but we should add a note saying that the reader should use Ubuntu 22.04 for the best results.

<hr />

In: **README.md**:

```
> Line 155
If the latency measurements indicate that latency has dropped by more than 5% compare to the previous uStreamer version, create some tickets.
```
What do we do if the latency gets worse? What if it gets worse but some other improvement (e.g., video quality) is notably improved?


<hr />

👀 @db39 it's your turn please take a look

2024-04-24 12:13 UTC, db39 reviewed
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/ustreamer-debian/20)



<hr />

In: **README.md**:

```
> Line 20
Open a GitHub comparison showing the commits since the last version of uStreamer TinyPilot uses to the latest tagged version e.g., [v5.43 to v6.11](https://github.com/pikvm/ustreamer/compare/v5.43...v6.11). Review the commit messages for any breaking changes or feature improvements.
```
Resolved

<hr />

In: **README.md**:

```
> Line 26
If the new version of uStreamer doesn't have any obvious breaking changes, create a new uStreamer debian package in a development branch.
```
Resolved

<hr />

In: **README.md**:

```
> Line 38
Create a new branch in this repository and update the `ARG PKG_VERSION=` line in `Dockerfile` to the desired [uStreamer release tag](https://github.com/pikvm/ustreamer/tags).
```
Resolved

<hr />

In: **README.md**:

```
> Line 42
When you have a branch for the new TinyPilot uStreamer Debian package, install the test package on a live device and test it.
```
Resolved

<hr />

In: **README.md**:

```
> Line 46
Download the TinyPilot uStreamer debian package.
```
Resolved

<hr />

In: **README.md**:

```
> Line 53
Run:
```
Resolved

<hr />

In: **README.md**:

```
> Line 68
Now perform a manual test of TinyPilot's video features (a subset of our manual release testing process) to make sure they still work as expected.
```
Resolved

<hr />

In: **README.md**:

```
> Line 155
If the latency measurements indicate that latency has dropped by more than 5% compare to the previous uStreamer version, create some tickets.
```
Good question! I'm not sure - this isn't a situation we've encountered so far, and I don't think uStreamer has published any releases with increased latency at all. uStreamer is designed to be "lightweight and very quick", so I'd be surprised if latency is ever compromised in favor of other features. My gut feeling is that we don't want to sacrifice latency.

If we test greater latency, it could also suggest the test setup / method isn't producing the expected results.

It would be great to get input from @shalver-tp / @mtlynch on this.


<hr />

👀 @cghague it's your turn please take a look

2024-04-24 15:52 UTC, mtlynch reviewed
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/ustreamer-debian/20)



<hr />

In: **README.md**:

```
> Line 155
If the latency measurements indicate that latency has dropped by more than 5% compare to the previous uStreamer version, create some tickets.
```
Yep, that's correct. We've never observed a regression in upgrading uStreamer.

If we encounter any regression (including a significant increase in latency) during the testing process, I think we'd just handle it on a case-by-case basis and raise it up with the product owner. 

The next steps would probably be one or more of these steps:

1. See if we can fix the uStreamer regression and contribute it upstream
1. Report the bug to uStreamer
1. Accept the regression if it's minor


<hr />

👀 @cghague, @db39 it's your turn please take a look

2024-04-25 11:56 UTC, db39 reviewed
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/ustreamer-debian/20)



<hr />

In: **README.md**:

```
> Line 161
If the latency measurements indicate that latency has dropped by more than 5% compare to the previous uStreamer version, create some tickets.
```
Thanks, Michael! I've added this to the doc.


<hr />

👀 @cghague it's your turn please take a look

2024-04-26 12:40 UTC, merged