Update to uStreamer 6.31
tiny-pilot/ustreamer-debian pull request #21
Opened 2024-04-23 12:19 UTC by db39

Resolves #19

uStreamer V6.31 has performance and stability improvements along with backend support for microphones (i.e., audio forwarding).

<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/ustreamer-debian/21"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>

2024-04-23 12:20 UTC, db39 commented
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/ustreamer-debian/21)

⏳ @cghague please review this Pull Request

2024-04-24 03:11 UTC, cghague requested changes
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/ustreamer-debian/21)


⏳ Approval Pending (1 unresolved comments)
_Approval will be granted automatically when all comments are resolved_

LGTM

<hr />

In: **Discussion**
Suggest: Add a description to the pull request explaining why we've cut a release for this version and confirming what [tests we've run](https://github.com/tiny-pilot/tinypilot/issues/1777#issuecomment-2058822415).


<hr />

👀 @db39 it's your turn please take a look

2024-04-26 12:06 UTC, db39 reviewed
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/ustreamer-debian/21)



<hr />

In: **Discussion**
Good idea, thanks!

I've tested V6.11 against our manual video tests, but I haven't measured video latency. I don't really have a suitable testbench for latency testing right now - is this something you can take on? I think it would make sense to test latency before cutting the release.


<hr />

👀 @cghague it's your turn please take a look

2024-05-15 01:52 UTC, cghague requested changes
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/ustreamer-debian/21)


⏳ Approval Pending (1 unresolved comments)
_Approval will be granted automatically when all comments are resolved_

<hr />

In: **Discussion**
I will have access to a suitable test environment once I return to my office, but that could be some time away. I'd recommend checking with the rest of the team so we don't delay the release.


<hr />

👀 @db39 it's your turn please take a look

2024-05-29 11:19 UTC, db39 commented
Since the update to 6.11 isn't high-priority, we've decided to push back cutting the release until we can test latency.

2025-02-19 21:37 UTC, cghague commented
@db39 - Numerous uStreamer releases have occurred since you made this pull request. I've skimmed through the commit log, and notable improvements include additional video formats and two-way audio support. Do you want to update this change to use a newer release?

2025-02-20 15:43 UTC, db39 commented
I've installed and tested 6.31. It seems mostly ok, but I wasn't able to get an H.264 stream working - even with a STUN server ([logs](https://logs.tinypilotkvm.com/zjLVitRE)). We may need to look into this. It's possible `ustreamer` has had a breaking change.

On another note, it looks like there are new 'No Signal' images, including a larger 1920x1080 version:

![TinyPilot-2025-02-20T15_29_02 950Z](https://github.com/user-attachments/assets/dd3270aa-58e2-43e6-817e-b922e34ea92b)

2025-02-22 00:14 UTC, cghague commented
Thanks, @db39. That's unfortunate! I've skimmed through the commits made since we last updated uStreamer, but there are no obvious breaking changes. The logs are somewhat different but generally look good. Is it possible that H.264 is working, but our method for detecting that H.264 is active has broken? If not, should we try a few smaller version jumps to narrow down where uStreamer introduced the breaking change?

2025-02-25 12:53 UTC, db39 commented
>Is it possible that H.264 is working, but our method for detecting that H.264 is active has broken? 

Possibly? I'm not that familiar with how we handle H.264 though. Could it be Janus related?

>If not, should we try a few smaller version jumps to narrow down where uStreamer introduced the breaking change?

We could, but it may be a lot of work narrowing down the issue - we'd have to try a few different builds. I'll look into this a little more.

2025-03-06 15:29 UTC, db39 commented
I've tested a few different versions of `ustreamer` to narrow down where H.264 streaming stops working.

If I run `ustreamer` 6.23, H.264 works, but H.264 stops working from version 6.24.

I haven't explored the details, but here are the [changes between the two versions](https://github.com/pikvm/ustreamer/compare/v6.23...v6.24) - refactoring and the introduction of microphone support.

For now, I think it's sensible to push a `ustreamer` update until the next release so we can properly update our integration to work with the latest version.

2025-03-07 03:59 UTC, cghague commented
Thanks for investigating, @db39! I agree with your conclusion; let's hold this back until our next release. If I were to guess, our front end doesn't expect an audio stream and is aborting as it doesn't know what to do.

2025-03-18 12:29 UTC, db39 commented
@cghague - Are you interested in taking over this issue considering this `ustreamer` update should allow us to take advantage of audio forwarding? I'm thinking you'll be able to better understand more of the interface changes and the work we'll need to do to implement audio based on the work you've already done.

2025-04-09 11:37 UTC, closed without merging